VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|

    if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'vagrant'
    end
    config.vm.box = "ubuntu/bionic64" # Chọn box bạn muốn sử dụng

    # Khởi tạo máy ảo thứ nhất
    config.vm.define "machine1" do |machine1|
    machine1.vm.network "private_network", ip: "192.168.56.2"
    machine1.vm.provider "virtualbox" do |vb|
          vb.memory = "2048" # 2GB RAM
          vb.cpus = 1       # 1 core CPU
        end

    machine1.vm.provision "shell", inline: <<-SHELL
          adduser airflow
          sudo su - airflow -c $'\
          whoami && \
          mkdir .ssh && \
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH21d4cu32i7EIKut9zcgrov5PiZfKATWdkrOUPSb9CbbaNjVKs/pntDMZuycwIDoIwVxmzyhUNx5tuflwRHUwwDaLEYv17AaIYTnZtL+IN4G1BAnFqqNTBVnrEVzjQqh+AVsI/G8fvUz56zM+N3Zonpz3o4C9KcHXHlMDFwu/yxiaH57QmL0+t2Unly3nOhjwqsZR1JFy+d71jYcWzadEgenjDX9AU4xgVGJDFgwBJ+eR3L31QmBd9A/uTylhXikn0oYVce1vFOx7VyTjD3Qxrwo74ABi9tE8ThRKy+LNsc79qYFHJobz7GUM3MWTvxlQzY3kZYtS2v2wFBiQzDGP long@Long-Laptop" > .ssh/authorized_keys && \
          chmod 700 .ssh && \
          chmod 600 .ssh/authorized_keys && \
          file_path=".ssh/authorized_keys" && \
          echo "cat file $file_path after make change" && \
          cat $file_path '
        SHELL
    end
    # cai cho /etc/sudoers.d/trino dat ten la gi cung dc, tham chi apeend vao file da co thi cx oke

    # Khởi tạo máy ảo thứ hai
    config.vm.define "machine2" do |machine2|
    machine2.vm.network "private_network", ip: "192.168.56.3"
    machine2.vm.provider "virtualbox" do |vb|
          vb.memory = "2048" # 2GB RAM
          vb.cpus = 1       # 1 core CPU
        end

    machine2.vm.provision "shell", inline: <<-SHELL
            adduser airflow
            sudo su - airflow -c $'\
            whoami && \
            mkdir .ssh && \
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH21d4cu32i7EIKut9zcgrov5PiZfKATWdkrOUPSb9CbbaNjVKs/pntDMZuycwIDoIwVxmzyhUNx5tuflwRHUwwDaLEYv17AaIYTnZtL+IN4G1BAnFqqNTBVnrEVzjQqh+AVsI/G8fvUz56zM+N3Zonpz3o4C9KcHXHlMDFwu/yxiaH57QmL0+t2Unly3nOhjwqsZR1JFy+d71jYcWzadEgenjDX9AU4xgVGJDFgwBJ+eR3L31QmBd9A/uTylhXikn0oYVce1vFOx7VyTjD3Qxrwo74ABi9tE8ThRKy+LNsc79qYFHJobz7GUM3MWTvxlQzY3kZYtS2v2wFBiQzDGP long@Long-Laptop" > .ssh/authorized_keys && \
            chmod 700 .ssh && \
            chmod 600 .ssh/authorized_keys && \
            file_path=".ssh/authorized_keys" && \
            echo "cat file $file_path after make change" && \
            cat $file_path '

        SHELL
    end
end